export const COMBAT_TUNING = Object.freeze({
  actionCap: 72,
  techniquePointCap: 3,
  techniqueCost: 2,
  sharedAidCost: 3,
  basicActionPower: 4,
  damageVarianceMin: -1,
  damageVarianceMax: 2,
  braceEarlyGuard: 18,
  braceUnderPressureGuard: 26,
  bracePressureHealthRatio: 0.6,
  bracePressureStrain: 2,
  heavyHitPower: 11,
  followUpBonusPower: 6,
  firstAidAmount: 24,
  sharedAidAmount: 16,
  quickHelpGuard: 7,
  quickHelpHealthRatio: 1 / 3,
  finishWeakHealthRatio: 0.5,
  rearStrikePower: 40,
  rearStrikeInterval: 3,
  coverRearGuard: 8,
  lineHitPower: 6,
  breakThreshold: 3,
  breakBonusPower: 8,
  breakDefencePenalty: 5,
  holdFrontStartingGuard: 18,
});

export type CombatTuning = typeof COMBAT_TUNING;
